server:
  port: 8086

spring:
  application:
    name: report-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/ntt_report
      auto-index-creation: true
  kafka:
    consumer:
      group-id: report-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

